/**
 * SANDBOX REST API
 * Welcome to the Rest API documentation. Don't have API keys? Login or create an account <a href=\"https://restapi.appspaces.ca/\">here</a> to get started.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.shiptime.demo.dto.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


/**
 * Represents the items in a commercial/customs invoice. Note that many carriers require the total insured value amount of a shipment to not exceed total customs value amount
 */
public class InvoiceItemModel   {
  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("origin")
  private String origin = null;

  @SerializedName("provinceOrState")
  private String provinceOrState = null;

  @SerializedName("unitPrice")
  private Integer unitPrice = null;

  @SerializedName("weight")
  private Float weight = null;

  public InvoiceItemModel quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity of the item
   * @return quantity
  **/
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public InvoiceItemModel code(String code) {
    this.code = code;
    return this;
  }

   /**
   * HS Code - 6 characters or 10 characters
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public InvoiceItemModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the item. Maximum: 50 characters
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InvoiceItemModel origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Country of Origin
   * @return origin
  **/
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public InvoiceItemModel provinceOrState(String provinceOrState) {
    this.provinceOrState = provinceOrState;
    return this;
  }

   /**
   * Province of Origin. Required by some carriers (ex. CanadaPost) when country of origin is CA
   * @return provinceOrState
  **/
  public String getProvinceOrState() {
    return provinceOrState;
  }

  public void setProvinceOrState(String provinceOrState) {
    this.provinceOrState = provinceOrState;
  }

  public InvoiceItemModel unitPrice(Integer unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Unit price of one line item represented in cents
   * @return unitPrice
  **/
  public Integer getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(Integer unitPrice) {
    this.unitPrice = unitPrice;
  }

  public InvoiceItemModel weight(Float weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Weight of one line item. Note that most carriers require that total invoice weight of invoice items does not exceed the weight of shipment.
   * @return weight
  **/
  public Float getWeight() {
    return weight;
  }

  public void setWeight(Float weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceItemModel invoiceItemModel = (InvoiceItemModel) o;
    return Objects.equals(this.quantity, invoiceItemModel.quantity) &&
        Objects.equals(this.code, invoiceItemModel.code) &&
        Objects.equals(this.description, invoiceItemModel.description) &&
        Objects.equals(this.origin, invoiceItemModel.origin) &&
        Objects.equals(this.provinceOrState, invoiceItemModel.provinceOrState) &&
        Objects.equals(this.unitPrice, invoiceItemModel.unitPrice) &&
        Objects.equals(this.weight, invoiceItemModel.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, code, description, origin, provinceOrState, unitPrice, weight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceItemModel {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    provinceOrState: ").append(toIndentedString(provinceOrState)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

