/**
 * SANDBOX REST API
 * Welcome to the Rest API documentation. Don't have API keys? Login or create an account <a href=\"https://restapi.appspaces.ca/\">here</a> to get started.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.shiptime.demo.dto.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;


/**
 * Rate response
 */
public class RateResponse   {
  @SerializedName("availableRates")
  private List<QuoteModel> availableRates = new ArrayList<QuoteModel>();

  @SerializedName("messages")
  private List<String> messages = new ArrayList<String>();

  public RateResponse availableRates(List<QuoteModel> availableRates) {
    this.availableRates = availableRates;
    return this;
  }

  public RateResponse addAvailableRatesItem(QuoteModel availableRatesItem) {
    this.availableRates.add(availableRatesItem);
    return this;
  }

   /**
   * List of available rates
   * @return availableRates
  **/
  public List<QuoteModel> getAvailableRates() {
    return availableRates;
  }

  public void setAvailableRates(List<QuoteModel> availableRates) {
    this.availableRates = availableRates;
  }

  public RateResponse messages(List<String> messages) {
    this.messages = messages;
    return this;
  }

  public RateResponse addMessagesItem(String messagesItem) {
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Messages
   * @return messages
  **/
  public List<String> getMessages() {
    return messages;
  }

  public void setMessages(List<String> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RateResponse rateResponse = (RateResponse) o;
    return Objects.equals(this.availableRates, rateResponse.availableRates) &&
        Objects.equals(this.messages, rateResponse.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableRates, messages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RateResponse {\n");
    
    sb.append("    availableRates: ").append(toIndentedString(availableRates)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

