/**
 * SANDBOX REST API
 * Welcome to the Rest API documentation. Don't have API keys? Login or create an account <a href=\"https://restapi.appspaces.ca/\">here</a> to get started.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.shiptime.demo.dto.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


/**
 * Surcharge Info
 */
public class SurchargeModel   {
  @SerializedName("price")
  private MoneyAmountModel price = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  public SurchargeModel price(MoneyAmountModel price) {
    this.price = price;
    return this;
  }

   /**
   * Price
   * @return price
  **/
  public MoneyAmountModel getPrice() {
    return price;
  }

  public void setPrice(MoneyAmountModel price) {
    this.price = price;
  }

  public SurchargeModel code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Surcharge Code
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SurchargeModel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Surcharge Name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SurchargeModel surchargeModel = (SurchargeModel) o;
    return Objects.equals(this.price, surchargeModel.price) &&
        Objects.equals(this.code, surchargeModel.code) &&
        Objects.equals(this.name, surchargeModel.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, code, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SurchargeModel {\n");
    
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

